name: Check step 1, Trigger a job based on labels

# This step triggers after 0-start.yml
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time we push to the deploy-staging.yml file on the staging-workflow branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - staging-workflow
    paths:
      - .github/workflows/deploy-staging.yml

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # The purpose of this job is to output the current step number 
  # (retreived from the STEP file). This output variable can
  # then be referenced in other jobs and used in conditional 
  # expressions.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_staging_workflow_update:
    name: On staging workflow update
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 1 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'TBD-organization'
        && needs.get_current_step.outputs.current_step == 1 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner added the specific label triggers
      - name: Verify workflow
        run: ./.github/script/check-file.sh
        env:
          FILE: .github/workflows/deploy-staging.yml
          SEARCH: "github.event.pull_request.labels\\.\\*.name.*stage"

      # Update README to close <details id=1>
      # and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        run: ./.github/script/update-step.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_STEP: 1
          TO_STEP: 2
          BRANCH_NAME: staging-workflow
