name: Check step 2, Set up the Azure environment

# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run every time we push to the deploy-staging.yml file on the staging-workflow branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - staging-workflow
    paths:
      - .github/workflows/deploy-staging.yml

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write
  pull-requests: write

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/script/STEP)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_staging_workflow_update:
    name: On staging workflow update
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 2
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner configured Build-Docker-Image job
      - name: Verify Build-Docker-Image job
        run: .github/script/check-file.sh
        env:
          FILE: .github/workflows/deploy-staging.yml
          SEARCH_LIST: 'Build-Docker-Image actions/download-artifact docker/login-action docker/build-push-action'

      # Verify the learner configured the Deploy-to-Azure job
      - name: Verify Deploy-to-Azure job
        run: .github/script/check-file.sh
        env:
          FILE: .github/workflows/deploy-staging.yml
          SEARCH_LIST: 'Deploy-to-Azure azure/login azure/webapps-deploy'

      # Merge the pull open pull request
      - name: Merge Pull Request
        run: gh pr merge --squash staging-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Pull main
      - name: Pull main
        run: ./.github/script/pull-main.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update README to close <details id=2> and open <details id=3>
      # and set STEP to '3'
      - name: Update to step 3
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
