name: Check step 3, Spin up environment

# This step sets STEP to 4
# This step closes <details id=3> and opens <details id=4>

# This will run after the "Configure Azure environment" workflow
# completes on the azure-configuration branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Configure Azure environment"]
    types: [completed]
    branches: [azure-configuration]

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write
  pull-requests: write

jobs:
  # The purpose of this job is to output the current step number 
  # (retreived from the STEP file). This output variable can
  # then be referenced in other jobs and used in conditional 
  # expressions.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_push:
    name: On push to azure-configuration
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 4 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'TBD-organization'
        && needs.get_current_step.outputs.current_step == 3 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Merge the pull open pull request
      - name: Merge Pull Request
        run: gh pr merge --squash azure-configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create pull request from staging-test to set up next step
      - name: Create staging-test pull request 
        run: .github/script/create-workflow-pr.sh --pull-first
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: staging-test
          PR_TITLE: 'Step 4, apply stage label'

      # Update README to close <details id=3>
      # and open <details id=4>
      # and set STEP to '4'
      - name: Update to step 4
        run: ./.github/script/update-step.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_STEP: 3
          TO_STEP: 4
          BRANCH_NAME: azure-configuration