name: Step 4, Deploy to staging

# This workflow updates from step 4 to step 5.

# This will run after the "Configure Azure environment" workflow
# completes on the azure-configuration branch
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to staging"]
    types: [completed]
    branches: [staging-test]

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write
  pull-requests: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_azure_environment_created:
    name: On Azure environment created
    needs: get_current_step
    runs-on: ubuntu-latest

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 4.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 4 }}

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches.

      # Merge the pull open pull request
      - name: Merge Pull Request
        run: gh pr merge --squash staging-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Pull main.
      - name: Pull main
        run: ./.github/script/pull-main.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # In README.md, switch step 4 for step 5.
      - name: Update to step 5
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: 5
          branch_name: staging-test
